### ISSUE TITLE
add license to repo, possibly to source file(s)

### ISSUE THREAD

**Issue by GitMensch** [contextfreecode/cobol-explore#4]
possibly with the online editor which would suggest a license and allows to choose - so you don't have to copy-paste the license info in manually; a one-liner on the license of the file - at least in game.cbl would likely be useful, too

Please see [GH Docs: Adding a license to a repository](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) - it should be done within 5 minutes (including the reading).

**Comment by tjpalmer** [comment]
Added an MIT license. Thanks for the issue!
